# -*- coding: utf-8 -*-
"""numpyx.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcuoZpqTO0tyenYcER3qepiCXPDCJshg
"""

#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
result = np.dot(arr1, arr2)
print(result)

#  How to find common values between two arrays?
import numpy as np
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
commons = np.intersect1d(arr1, arr2)
print(commons)

# Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
arr = np.zeros((5,5), dtype=int)
arr = arr + np.arange(5)
print(arr)

# Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
arr = np.linspace(0,1, 12)
print(arr[1:-1])

# Consider two random arrays A and B, check if they are equal
import numpy as np
A = np.random.randint(0,5, 10, dtype=int)
B = np.random.randint(0,5, 10, dtype=int)
is_equal = np.array_equal(A, B)
print(is_equal)

# Create random vector of size 10 and replace the maximum value by 0
import numpy as np
arr = np.random.rand(10)
arr[arr.argmax()] = 0
print(arr)

# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

# Print the minimum and maximum representable values for each numpy scalar type
import numpy as np
int8 = np.iinfo(np.int8)
# print(int8.max)
# print(int8.min)

int16 = np.iinfo(np.int16)
# print(int16.max)
# print(int16.min)

int32 = np.iinfo(np.int32)
# print(int32.max)
# print(int32.min)

int64 = np.iinfo(np.int64)
# print(int64.max)
# print(int64.min)

float32 = np.finfo(np.float32)
# print(float32.max)
# print(float32.min)

# How to print all the values of an array?
import numpy as np
import sys
arr = np.arange(1001)
np.set_printoptions(threshold=sys.maxsize)
print(arr)

# How to find the closest value (to a given scalar) in a vector?
import numpy as np
arr = np.array([1,3,4,5,7,8,8,9,9,34,56,77])
given_number = 40
i = np.abs(arr - given_number)
print(i.min() + given_number)

# How to convert a float (32 bits) array into an integer (32 bits) array in place?
arr = np.array([1.1, 2.5, 3.9, 4.2], dtype=np.float32)
arr[:] = arr.astype(np.int32)
print(arr)